version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8081:3000'
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "start"]